include: package:flutter_lints/flutter.yaml

analyzer: 
  errors: 
    prefer_single_quotes: warning
    avoid_empty_else: warning
    always_declare_return_types: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    sort_child_properties_last: warning
    use_key_in_widget_constructors: warning
    avoid_returning_null_for_void: warning
    cancel_subscriptions: warning
    close_sinks: warning
    avoid_web_libraries_in_flutter: warning
    prefer_const_constructors_in_immutables: warning
    sized_box_for_whitespace: warning
    use_build_context_synchronously: warning

linter:
  rules:
    prefer_single_quotes: true
    avoid_empty_else: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true