// Mocks generated by Mockito 5.4.4 from annotations
// in prototype/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i11;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prototype/data/models/category.dart' as _i3;
import 'package:prototype/data/models/location.dart' as _i14;
import 'package:prototype/data/models/order.dart' as _i8;
import 'package:prototype/data/models/product.dart' as _i10;
import 'package:prototype/data/models/route.dart' as _i16;
import 'package:prototype/presentation/state/auth_provider.dart' as _i6;
import 'package:prototype/presentation/state/category_provider.dart' as _i2;
import 'package:prototype/presentation/state/location_provider.dart' as _i13;
import 'package:prototype/presentation/state/order_provider.dart' as _i7;
import 'package:prototype/presentation/state/product_provider.dart' as _i9;
import 'package:prototype/presentation/state/route_provider.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryProvider extends _i1.Mock implements _i2.CategoryProvider {
  MockCategoryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Category> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i3.Category>[],
      ) as List<_i3.Category>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadCategories() => (super.noSuchMethod(
        Invocation.method(
          #loadCategories,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i3.Category? getById(String? id) => (super.noSuchMethod(Invocation.method(
        #getById,
        [id],
      )) as _i3.Category?);

  @override
  _i4.Future<void> addCategory(
    String? name,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [
            name,
            description,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCategory(
    String? id,
    Map<String, dynamic>? fields,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            fields,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i6.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isRestoring => (super.noSuchMethod(
        Invocation.getter(#isRestoring),
        returnValue: false,
      ) as bool);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OrderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderProvider extends _i1.Mock implements _i7.OrderProvider {
  MockOrderProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Order> get orders => (super.noSuchMethod(
        Invocation.getter(#orders),
        returnValue: <_i8.Order>[],
      ) as List<_i8.Order>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadOrders() => (super.noSuchMethod(
        Invocation.method(
          #loadOrders,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createOrder(List<Map<String, dynamic>>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [items],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateOrder(
    String? id,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [
            id,
            items,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteOrder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProductProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductProvider extends _i1.Mock implements _i9.ProductProvider {
  MockProductProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i10.Product>[],
      ) as List<_i10.Product>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createProduct({
    required String? name,
    required double? price,
    required int? stock,
    required String? description,
    required String? categoryId,
    List<_i11.File>? images,
    _i12.Uint8List? webImageBytes,
    String? webImageName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [],
          {
            #name: name,
            #price: price,
            #stock: stock,
            #description: description,
            #categoryId: categoryId,
            #images: images,
            #webImageBytes: webImageBytes,
            #webImageName: webImageName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProduct({
    required String? id,
    required String? name,
    required double? price,
    required int? stock,
    required String? description,
    required String? categoryId,
    List<_i11.File>? images,
    _i12.Uint8List? webImageBytes,
    String? webImageName,
    List<String>? existingImages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [],
          {
            #id: id,
            #name: name,
            #price: price,
            #stock: stock,
            #description: description,
            #categoryId: categoryId,
            #images: images,
            #webImageBytes: webImageBytes,
            #webImageName: webImageName,
            #existingImages: existingImages,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationProvider extends _i1.Mock implements _i13.LocationProvider {
  MockLocationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i14.Location> get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: <_i14.Location>[],
      ) as List<_i14.Location>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadLocations() => (super.noSuchMethod(
        Invocation.method(
          #loadLocations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createLocation({
    required String? name,
    required String? description,
    required String? address,
    List<_i11.File>? imageFiles,
    _i12.Uint8List? webImageBytes,
    String? webImageName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [],
          {
            #name: name,
            #description: description,
            #address: address,
            #imageFiles: imageFiles,
            #webImageBytes: webImageBytes,
            #webImageName: webImageName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLocation(
    String? id,
    Map<String, dynamic>? fields, {
    _i11.File? imageFile,
    _i12.Uint8List? webImageBytes,
    String? webImageName,
    List<String>? existingImages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            id,
            fields,
          ],
          {
            #imageFile: imageFile,
            #webImageBytes: webImageBytes,
            #webImageName: webImageName,
            #existingImages: existingImages,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLocation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RouteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteProvider extends _i1.Mock implements _i15.RouteProvider {
  MockRouteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i16.RouteModel> get routes => (super.noSuchMethod(
        Invocation.getter(#routes),
        returnValue: <_i16.RouteModel>[],
      ) as List<_i16.RouteModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadRoutes() => (super.noSuchMethod(
        Invocation.method(
          #loadRoutes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createRoute({
    required String? name,
    required String? grade,
    required String? locationId,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoute,
          [],
          {
            #name: name,
            #grade: grade,
            #locationId: locationId,
            #description: description,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRoute(
    String? id,
    Map<String, dynamic>? fields,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoute,
          [
            id,
            fields,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoute(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> rateRoute(
    String? id,
    String? grade,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateRoute,
          [
            id,
            grade,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
